import * as React from 'react';
import { useState } from 'react';
import { Wand2, Sparkles, MessageSquare } from 'lucide-react';
import { Textarea } from '@/shared/components/ui/textarea';
import { Button } from '@/shared/components/ui/button';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/shared/components/ui/tooltip';
import { LoadingSpinner } from '@/shared/components/LoadingSpinner';
import { getShortcutDisplay } from '@/shared/hooks/useKeyboardShortcuts';

export type PromptMode = 'generate' | 'edit';

interface PromptControlsProps {
  prompt: string;
  onPromptChange: (value: string) => void;
  onGenerate: () => void;
  isLoading: boolean;
  mode?: PromptMode;
  onModeChange?: (mode: PromptMode) => void;
  autoGeneratedPrompt?: string;
  onAskAgent?: (prompt: string) => void;
  isAskingAgent?: boolean;
  showGenerateAction?: boolean;
  showAgentAction?: boolean;
  submitOnEnter?: boolean;
  placeholderOverride?: string;
}

export const PromptControls: React.FC<PromptControlsProps> = ({
  prompt,
  onPromptChange,
  onGenerate,
  isLoading,
  mode = 'generate',
  onModeChange,
  autoGeneratedPrompt,
  onAskAgent,
  isAskingAgent = false,
  showGenerateAction = true,
  showAgentAction = false,
  submitOnEnter = false,
  placeholderOverride,
}) => {
  const [isFlipping, setIsFlipping] = useState(false);
  const isDisabled = isLoading || prompt.length < 10;
  const askDisabled = !prompt.trim() || isAskingAgent;
  const generateShortcut = getShortcutDisplay({ key: 'g', ctrl: true, handler: () => { } });

  const handleModeToggle = (): void => {
    if (!onModeChange || isFlipping) return;

    setIsFlipping(true);
    setTimeout(() => {
      const newMode = mode === 'generate' ? 'edit' : 'generate';
      onModeChange(newMode);

      if (newMode === 'edit' && autoGeneratedPrompt) {
        onPromptChange(autoGeneratedPrompt);
      }

      setTimeout(() => setIsFlipping(false), 300);
    }, 150);
  };

  const placeholderText = placeholderOverride ?? (mode === 'generate'
    ? 'Describe your scene... minimum 10 characters'
    : 'Describe your modifications... (e.g., "add sunlight, make it warmer")');

  const buttonLabel = mode === 'generate' ? 'Generate' : 'Refine';
  const buttonIcon = mode === 'generate' ? <Wand2 className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />;

  return (
    <TooltipProvider>
      <div className="flex gap-3 items-end p-2 rounded-xl bg-card/40 border border-border/50 studio-blur animate-reveal">
        <div
          className="flex-1 relative group"
          style={{
            perspective: '1000px',
          }}
        >
          <div
            className={`transition-all duration-300 ${isFlipping ? 'animate-flip' : ''}`}
            style={{
              transformStyle: 'preserve-3d',
            }}
          >
            <Textarea
              id="prompt-input"
              value={prompt}
              onChange={(e) => onPromptChange(e.target.value)}
              onKeyDown={(e) => {
                if (!submitOnEnter || !onAskAgent) return;
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  if (!askDisabled) {
                    onAskAgent(prompt);
                  }
                }
              }}
              placeholder={placeholderText}
              rows={2}
              aria-label={placeholderText}
              aria-required="true"
              className="resize-none border-none bg-transparent focus-visible:ring-0 focus-visible:ring-offset-0 text-sm py-2 px-1 placeholder:text-muted-foreground/50 transition-all duration-200"
            />
            {/* Subtle focus line anim */}
            <div className="absolute bottom-0 left-0 h-[1.5px] bg-primary scale-x-0 group-focus-within:scale-x-100 transition-transform duration-300 origin-left w-full shadow-sm shadow-primary/30" />
          </div>
        </div>

        <div className="flex items-center gap-1.5 pb-0.5">
          {onModeChange && showGenerateAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  onClick={handleModeToggle}
                  disabled={isFlipping}
                  className="relative h-7 w-12 rounded-full border border-border/50 bg-muted/30 transition-all hover:bg-muted/50 disabled:opacity-50"
                  aria-label="Toggle between Generate and Edit modes"
                >
                  <div
                    className={`absolute top-0.5 left-0.5 h-6 w-6 rounded-full bg-primary/90 studio-glow transition-all duration-300 flex items-center justify-center ${mode === 'edit' ? 'translate-x-5' : 'translate-x-0'
                      }`}
                  >
                    {mode === 'generate' ? (
                      <Wand2 className="h-3 w-3 text-primary-foreground" />
                    ) : (
                      <Sparkles className="h-3 w-3 text-primary-foreground" />
                    )}
                  </div>
                </button>
              </TooltipTrigger>
              <TooltipContent side="top">
                <p className="text-xs font-medium">
                  {mode === 'generate'
                    ? 'Switch to Edit mode'
                    : 'Switch to Generate mode'}
                </p>
              </TooltipContent>
            </Tooltip>
          )}

          <div className='w-px h-5 bg-border/40 mx-0.5' />

          {onAskAgent && showAgentAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  onClick={() => onAskAgent(prompt)}
                  disabled={askDisabled}
                  size="icon"
                  variant="ghost"
                  className="rounded-lg h-8 w-8 transition-all duration-200 hover:bg-primary/10 hover:text-primary active:scale-95"
                  aria-label="Ask Penguin Agent"
                >
                  <MessageSquare className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="top">
                <p className="text-xs font-medium">Ask Agent</p>
              </TooltipContent>
            </Tooltip>
          )}

          {showGenerateAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="inline-block outline-none rounded-lg" tabIndex={isDisabled ? 0 : -1}>
                  <Button
                    onClick={() => onGenerate()}
                    disabled={isDisabled}
                    size="icon"
                    className={`rounded-lg h-9 w-9 transition-all duration-300 shadow-sm ${!isDisabled ? 'bg-primary hover:bg-primary/90 studio-glow active:scale-90' : 'bg-muted/50 cursor-not-allowed opacity-50 pointer-events-none'
                      }`}
                    aria-label={`${buttonLabel} image`}
                  >
                    {isLoading ? <LoadingSpinner size="sm" /> : buttonIcon}
                  </Button>
                </span>
              </TooltipTrigger>
              <TooltipContent side="top">
                {isLoading ? (
                  <p className="text-xs font-semibold">Generating...</p>
                ) : isDisabled ? (
                  <p className="text-xs font-semibold text-destructive">Enter at least 10 characters</p>
                ) : (
                  <p className="text-xs font-semibold">{buttonLabel} <span className="text-[10px] opacity-70 font-normal ml-1">({generateShortcut})</span></p>
                )}
              </TooltipContent>
            </Tooltip>
          )}
        </div>
      </div>

      <style>{`
        @keyframes flip {
          0% {
            transform: rotateX(0deg);
          }
          50% {
            transform: rotateX(90deg);
          }
          100% {
            transform: rotateX(0deg);
          }
        }
        .animate-flip {
          animation: flip 0.3s ease-in-out;
        }
      `}</style>
    </TooltipProvider>
  );
};
