import * as React from 'react';
import { useState } from 'react';
import { Wand2, Sparkles, MessageSquare } from 'lucide-react';
import { Textarea } from '@/shared/components/ui/textarea';
import { Button } from '@/shared/components/ui/button';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/shared/components/ui/tooltip';
import { getShortcutDisplay } from '@/shared/hooks/useKeyboardShortcuts';

export type PromptMode = 'generate' | 'edit';

interface PromptControlsProps {
  prompt: string;
  onPromptChange: (value: string) => void;
  onGenerate: () => void;
  isLoading: boolean;
  mode?: PromptMode;
  onModeChange?: (mode: PromptMode) => void;
  autoGeneratedPrompt?: string;
  onAskAgent?: (prompt: string) => void;
  isAskingAgent?: boolean;
  showGenerateAction?: boolean;
  showAgentAction?: boolean;
  submitOnEnter?: boolean;
  placeholderOverride?: string;
}

export const PromptControls: React.FC<PromptControlsProps> = ({
  prompt,
  onPromptChange,
  onGenerate,
  isLoading,
  mode = 'generate',
  onModeChange,
  autoGeneratedPrompt,
  onAskAgent,
  isAskingAgent = false,
  showGenerateAction = true,
  showAgentAction = false,
  submitOnEnter = false,
  placeholderOverride,
}) => {
  const [isFlipping, setIsFlipping] = useState(false);
  const isDisabled = isLoading || prompt.length < 10;
  const askDisabled = !prompt.trim() || isAskingAgent;
  const generateShortcut = getShortcutDisplay({ key: 'g', ctrl: true, handler: () => { } });

  const handleModeToggle = (): void => {
    if (!onModeChange || isFlipping) return;

    setIsFlipping(true);
    setTimeout(() => {
      const newMode = mode === 'generate' ? 'edit' : 'generate';
      onModeChange(newMode);

      if (newMode === 'edit' && autoGeneratedPrompt) {
        onPromptChange(autoGeneratedPrompt);
      }

      setTimeout(() => setIsFlipping(false), 300);
    }, 150);
  };

  const placeholderText = placeholderOverride ?? (mode === 'generate'
    ? 'Describe your scene... minimum 10 characters'
    : 'Describe your modifications... (e.g., "add sunlight, make it warmer")');

  const buttonLabel = mode === 'generate' ? 'Generate' : 'Refine';
  const buttonIcon = mode === 'generate' ? <Wand2 className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />;

  return (
    <TooltipProvider>
      <div className="flex gap-2 items-start">
        <div
          className="flex-1 relative"
          style={{
            perspective: '1000px',
          }}
        >
          <div
            className={`transition-all duration-300 ${isFlipping ? 'animate-flip' : ''}`}
            style={{
              transformStyle: 'preserve-3d',
            }}
          >
            <Textarea
              id="prompt-input"
              value={prompt}
              onChange={(e) => onPromptChange(e.target.value)}
              onKeyDown={(e) => {
                if (!submitOnEnter || !onAskAgent) return;
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  if (!askDisabled) {
                    onAskAgent(prompt);
                  }
                }
              }}
              placeholder={placeholderText}
              rows={3}
              aria-describedby="prompt-help"
              aria-required="true"
              className="resize-none transition-all duration-150 focus:ring-2 text-sm"
            />
          </div>
        </div>

        <div className="flex flex-col gap-1">
          {onModeChange && showGenerateAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  onClick={handleModeToggle}
                  disabled={isFlipping}
                  className="relative h-7 w-12 rounded-full bg-muted transition-colors hover:bg-muted/80 disabled:opacity-50"
                  aria-label="Toggle between Generate and Edit modes"
                >
                  <div
                    className={`absolute top-0.5 left-0.5 h-6 w-6 rounded-full bg-primary transition-transform duration-200 flex items-center justify-center ${mode === 'edit' ? 'translate-x-5' : 'translate-x-0'
                      }`}
                  >
                    {mode === 'generate' ? (
                      <Wand2 className="h-3 w-3 text-primary-foreground" />
                    ) : (
                      <Sparkles className="h-3 w-3 text-primary-foreground" />
                    )}
                  </div>
                </button>
              </TooltipTrigger>
              <TooltipContent>
                <p className="text-xs">
                  {mode === 'generate'
                    ? 'Switch to Edit mode to refine with modifications'
                    : 'Switch to Generate mode for new images'}
                </p>
              </TooltipContent>
            </Tooltip>
          )}
          <div className='mt-2' />
          {onAskAgent && showAgentAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  onClick={() => onAskAgent(prompt)}
                  disabled={askDisabled}
                  size="sm"
                  variant="secondary"
                  className="rounded-full h-8 px-2 transition-all duration-150 hover:scale-[1.02] active:scale-[0.98]"
                  aria-label="Ask Penguin Agent"
                >
                  <MessageSquare className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p className="text-xs">Ask Agent</p>
              </TooltipContent>
            </Tooltip>
          )}
          {showGenerateAction && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  onClick={onGenerate}
                  disabled={isDisabled}
                  size="sm"
                  className="rounded-full h-8 px-2 transition-all duration-150 hover:scale-[1.02] active:scale-[0.98]"
                  aria-label={`${buttonLabel} image from configuration (${generateShortcut})`}
                >
                  {buttonIcon}
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p className="text-xs">{buttonLabel} ({generateShortcut})</p>
              </TooltipContent>
            </Tooltip>
          )}
        </div>
      </div>

      <style>{`
        @keyframes flip {
          0% {
            transform: rotateX(0deg);
          }
          50% {
            transform: rotateX(90deg);
          }
          100% {
            transform: rotateX(0deg);
          }
        }
        .animate-flip {
          animation: flip 0.3s ease-in-out;
        }
      `}</style>
    </TooltipProvider>
  );
};
