import { useState, useEffect, useImperativeHandle, forwardRef, useRef, Suspense, lazy } from 'react';
import { ImageViewer } from '@/features/imageEdit/components/ImageViewer';
// import { MaskViewer } from '@/features/segmentation/components/MaskViewer';
// import { PromptControls, type PromptMode } from '@/shared/components/PromptControls';
import type { PromptMode } from '@/shared/components/PromptControls';
import { ErrorOverlay } from '@/shared/components/ErrorOverlay';
import { useConfigStore } from '@/features/scene/store/configStore';
import type { PenguinConfig, SceneConfiguration, SceneObject } from '@/core/types';
import { useSegmentationStore } from '@/features/segmentation/store/segmentationStore';
import { useGeneration } from '@/shared/hooks/useGeneration';
import { useDebounce } from '@/shared/hooks/useDebounce';
import { useMaskKeyboardShortcuts } from '@/features/segmentation/hooks/useMaskKeyboardShortcuts';
import { Button } from '@/shared/components/ui/button';
import { useFileSystemStore } from '@/core/store/fileSystemStore';
import { useLayoutStore } from '@/core/store/layoutStore';
import { editTracker } from '@/shared/lib/editTracker';
import { useChatStore } from '@/features/agentic/store/chatStore';

const MaskViewer = lazy(() => import('@/features/segmentation/components/MaskViewer').then(module => ({ default: module.MaskViewer })));
const PromptControls = lazy(() => import('@/shared/components/PromptControls').then(module => ({ default: module.PromptControls })));

export interface WorkspacePanelRef {
  handleGenerate: (promptOverride?: unknown) => void;
  handleGenerateFromPrompt: (prompt: string) => void;
  handleRefine: (promptOverride?: unknown) => void;
  handleRefineWithConfig: (
    configOverride: PenguinConfig,
    promptOverride?: unknown,
    structuredOverride?: Record<string, unknown>
  ) => void;
}

type ViewMode = 'original' | 'segmented';



export const WorkspacePanel = forwardRef<WorkspacePanelRef>((_props, ref) => {
  const shortDescription = useConfigStore((state) => state.config.short_description);
  const config = useConfigStore((state) => state.config);
  const updateConfig = useConfigStore((state) => state.updateConfig);
  const setWorkspaceHandlers = useLayoutStore((state) => state.setWorkspaceHandlers);
  const activeMode = useLayoutStore((state) => state.activeMode);
  const selectedFileUrl = useFileSystemStore((state) => state.selectedFileUrl);
  const currentGenerationId = useFileSystemStore((state) => state.currentGenerationId);
  const setOriginalStructuredPrompt = useFileSystemStore((state) => state.setOriginalStructuredPrompt);
  const sendAgentMessage = useChatStore((state) => state.sendMessage);
  const isAgentTyping = useChatStore((state) => state.isTyping);
  const connectAgent = useChatStore((state) => state.connect);


  const safeShortDescription = typeof shortDescription === 'string' ? shortDescription : '';
  const [localPrompt, setLocalPrompt] = useState(safeShortDescription);
  const [chatPrompt, setChatPrompt] = useState('');
  const debouncedPrompt = useDebounce(localPrompt, 300);
  const [viewMode, setViewMode] = useState<ViewMode>('original');
  const userViewModeOverrideRef = useRef(false);
  const [promptMode, setPromptMode] = useState<PromptMode>('generate');
  const [autoGeneratedPrompt, setAutoGeneratedPrompt] = useState<string>('');

  // Track if user has manually edited the prompt in edit mode (to avoid overwriting their changes)
  const userEditedPromptRef = useRef(false);

  const { generateImage, refineImage, setSeed, clearGeneratedImage, isLoading, generatedImage, error } = useGeneration();
  const currentSeed = useFileSystemStore((state) => state.currentSeed);
  const originalStructuredPrompt = useFileSystemStore((state) => state.originalStructuredPrompt);
  const [libraryImage, setLibraryImage] = useState<string | null>(null);
  const viewerStyle: React.CSSProperties = {
    width: '100%',
    height: 'calc(100vh - 300px)',
    maxHeight: 'calc(100vh - 150px)',
    minHeight: '360px',
  };

  const segmentationResults = useSegmentationStore((state) => state.results);
  const selectedMaskId = useSegmentationStore((state) => state.selectedMaskId);
  const isSegmenting = useSegmentationStore((state) => state.isProcessing);
  const segmentationError = useSegmentationStore((state) => state.error);
  const segmentationErrorCode = useSegmentationStore((state) => state.errorCode);
  const selectMask = useSegmentationStore((state) => state.selectMask);
  const hoverMask = useSegmentationStore((state) => state.hoverMask);
  const retryLastOperation = useSegmentationStore((state) => state.retryLastOperation);
  const resetConfig = useConfigStore((state) => state.resetConfig);

  useMaskKeyboardShortcuts({ enabled: viewMode === 'segmented' && !!segmentationResults });

  useEffect(() => {
    connectAgent();
  }, [connectAgent]);

  // Track if this is a fresh mount (no image context)
  const isInitialMountRef = useRef(true);

  // Reset config to defaults on initial mount if no image is loaded
  // This ensures fresh sessions start with empty/default config
  useEffect(() => {
    if (!isInitialMountRef.current) return;
    isInitialMountRef.current = false;

    const hasImage = generatedImage || selectedFileUrl || segmentationResults?.original_image_url;
    if (!hasImage) {
      // Clear persisted storage for truly fresh sessions
      try {
        localStorage.removeItem('penguin-config-storage');
      } catch (e) {
        console.warn('[WorkspacePanel] Failed to clear localStorage:', e);
      }
      resetConfig();
      setLocalPrompt('');
      baseUserPromptRef.current = '';
      editTracker.clearEdits();
    }
    // Only run on mount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Sync local prompt to config store (only when user types, not when config is loaded)
  useEffect(() => {
    if (activeMode !== 'edit') return;
    const safePrompt = typeof debouncedPrompt === 'string' ? debouncedPrompt : '';
    if (safePrompt !== safeShortDescription && promptMode === 'generate') {
      updateConfig('short_description', safePrompt);
    }
  }, [debouncedPrompt, safeShortDescription, updateConfig, promptMode, activeMode]);

  // Check if we have an image loaded (for determining edit behavior)
  // Use originalImageToShow calculation to be consistent
  const hasImageLoaded = !!(generatedImage || libraryImage || segmentationResults?.original_image_url);

  // Track the base prompt (user-typed portion) separately from edit additions
  const baseUserPromptRef = useRef('');

  // Sync config store to local prompt (when config is loaded externally)
  // Only sync if we're not currently editing and no edits are pending
  useEffect(() => {
    if (activeMode !== 'edit') return;
    if (editTracker.hasEdits()) return;

    const nextShort = safeShortDescription;
    if (nextShort !== localPrompt && promptMode === 'generate' && document.activeElement?.id !== 'prompt-input') {
      setLocalPrompt(nextShort);
      if (!hasImageLoaded) {
        baseUserPromptRef.current = nextShort;
      }
    }
  }, [safeShortDescription, localPrompt, promptMode, hasImageLoaded, activeMode]);

  // Live-update prompt based on edits
  // - If image is loaded and in edit mode: update refine prompt
  // - If no image is loaded: append edits to generation prompt in real-time
  useEffect(() => {
    if (activeMode !== 'edit') return;

    const unsubscribe = editTracker.subscribe(() => {
      const editPrompt = editTracker.getModificationPrompt();
      // console.log('[EditTracker] Edit changed:', { editPrompt, hasImageLoaded, promptMode });

      if (hasImageLoaded) {
        // Image loaded: only update when in edit mode
        if (promptMode === 'edit') {
          setAutoGeneratedPrompt(editPrompt);
          // Only update localPrompt if user hasn't manually edited it
          if (!userEditedPromptRef.current) {
            setLocalPrompt(editPrompt);
          }
        }
      } else {
        // No image loaded: always append edits to generation prompt
        const base = baseUserPromptRef.current || '';
        if (editPrompt) {
          const separator = base.trim() ? ', ' : '';
          const combinedPrompt = base.trim() + separator + editPrompt;
          // console.log('[EditTracker] Setting combined prompt:', combinedPrompt);
          setLocalPrompt(combinedPrompt);
        } else {
          // No edits, restore base prompt
          setLocalPrompt(base);
        }
      }
    });

    return unsubscribe;
  }, [promptMode, hasImageLoaded, activeMode]);

  // Track user's base prompt (before edits are appended)
  const handlePromptChange = (value: string): void => {
    setLocalPrompt(value);

    // If in edit mode with image loaded, mark that user has manually edited
    // BUT only if the value differs from the auto-generated prompt (actual user edit)
    if (hasImageLoaded && promptMode === 'edit' && value !== autoGeneratedPrompt) {
      userEditedPromptRef.current = true;
    }

    // If no image loaded, we need to track the base prompt
    if (!hasImageLoaded) {
      const editPrompt = editTracker.getModificationPrompt();

      if (!editPrompt) {
        // No edits, entire value is the base
        baseUserPromptRef.current = value;
      } else {
        // There are edits - extract the base prompt from the value
        // The format is: "base prompt, edit1 and edit2"
        // We need to find where the edit part starts
        if (value.endsWith(editPrompt)) {
          // User kept the edit suffix, extract the base
          const editStart = value.lastIndexOf(editPrompt);
          let base = value.substring(0, editStart);
          // Remove trailing ", " or " "
          base = base.replace(/,\s*$/, '').trim();
          baseUserPromptRef.current = base;
        } else {
          // User modified the prompt (including edit part)
          // Treat the entire value as the new base and clear edits
          baseUserPromptRef.current = value;
          editTracker.clearEdits();
        }
      }
    }
  };

  const configRef = useRef(config);
  const localPromptRef = useRef(localPrompt);
  const generatedImageRef = useRef<string | null>(generatedImage);
  const generateImageRef = useRef(generateImage);
  const refineImageRef = useRef(refineImage);
  const libraryImageRef = useRef<string | null>(null);
  const originalStructuredPromptRef = useRef<Record<string, unknown> | null>(originalStructuredPrompt);
  const selectedFileUrlRef = useRef<string | null>(selectedFileUrl);
  const currentGenerationIdRef = useRef<string | null>(currentGenerationId);
  const segmentationResultsRef = useRef(segmentationResults);

  useEffect(() => {
    configRef.current = config;
  }, [config]);

  useEffect(() => {
    localPromptRef.current = localPrompt;
  }, [localPrompt]);

  useEffect(() => {
    generatedImageRef.current = generatedImage;
  }, [generatedImage]);

  useEffect(() => {
    libraryImageRef.current = libraryImage;
  }, [libraryImage]);

  useEffect(() => {
    generateImageRef.current = generateImage;
  }, [generateImage]);

  useEffect(() => {
    refineImageRef.current = refineImage;
  }, [refineImage]);

  useEffect(() => {
    originalStructuredPromptRef.current = originalStructuredPrompt;
  }, [originalStructuredPrompt]);

  useEffect(() => {
    selectedFileUrlRef.current = selectedFileUrl;
  }, [selectedFileUrl]);

  useEffect(() => {
    currentGenerationIdRef.current = currentGenerationId;
  }, [currentGenerationId]);

  useEffect(() => {
    segmentationResultsRef.current = segmentationResults;
  }, [segmentationResults]);

  const hasVisualContext = (): boolean => {
    const hasSegmentationImage = !!segmentationResultsRef.current?.original_image_url;
    return Boolean(
      generatedImageRef.current ||
      libraryImageRef.current ||
      selectedFileUrlRef.current ||
      currentGenerationIdRef.current ||
      hasSegmentationImage
    );
  };

  const normalizePromptOverride = (value: unknown): string | undefined => {
    if (typeof value !== 'string') return undefined;
    const trimmed = value.trim();
    if (!trimmed || trimmed === '[object Object]') return undefined;
    return trimmed;
  };

  const resolveGenerationPrompt = (
    promptOverride?: unknown,
    configOverride?: PenguinConfig
  ): string => {
    const candidate = normalizePromptOverride(promptOverride) || '';
    if (candidate) return candidate;

    if (configOverride?.short_description?.trim()) {
      return configOverride.short_description.trim();
    }

    const local = (localPromptRef.current || '').trim();
    if (local) return local;

    const configShort = (configRef.current?.short_description || '').trim();
    if (configShort) return configShort;

    return 'A cinematic product photo scene';
  };

  const handleGenerate = (promptOverride?: unknown): void => {
    const normalizedOverride = normalizePromptOverride(promptOverride);
    if (promptMode === 'generate') {
      // Generate mode: uses just the text prompt (simple text-to-image)
      const rawPrompt = normalizedOverride ?? localPromptRef.current;
      const prompt =
        typeof rawPrompt === 'string' && rawPrompt !== '[object Object]'
          ? rawPrompt
          : safeShortDescription;

      if (!prompt || prompt === '[object Object]') {
        console.warn('[WorkspacePanel] Invalid prompt detected, aborting generate.');
        return;
      }

      generateImageRef.current?.(prompt);
    } else {
      // Edit mode: uses the modification prompt (user can edit the auto-generated one)
      handleRefine(normalizedOverride);
    }
  };

  const handleGenerateFromPrompt = (prompt: string): void => {
    const resolved = resolveGenerationPrompt(prompt, configRef.current);
    generateImageRef.current?.(resolved);
  };

  const buildObjectsFromSegmentationMetadata = (
    baseObjects: SceneObject[]
  ): SceneObject[] => {
    const masks = segmentationResultsRef.current?.masks;
    if (!masks || masks.length === 0) {
      return baseObjects;
    }

    const nextObjects = [...baseObjects];

    const isPlaceholderObject = (obj: SceneObject): boolean => {
      const description = typeof obj.description === 'string' ? obj.description.trim() : '';
      const shape = typeof obj.shape_and_color === 'string' ? obj.shape_and_color.trim() : '';
      const hasOptionalDetails = Boolean(
        (obj.relationship && String(obj.relationship).trim()) ||
        (obj.texture && String(obj.texture).trim()) ||
        (obj.appearance_details && String(obj.appearance_details).trim())
      );

      return (
        !description &&
        !shape &&
        !hasOptionalDetails &&
        obj.location === 'center' &&
        obj.relative_size === 'medium' &&
        obj.orientation === 'front-facing'
      );
    };

    const pickValue = (baseValue: unknown, metaValue: unknown, fallbackValue: unknown, preferMeta = false) => {
      const baseText = baseValue === undefined || baseValue === null ? '' : String(baseValue).trim();
      const metaText = metaValue === undefined || metaValue === null ? '' : String(metaValue).trim();
      const fallbackText = fallbackValue === undefined || fallbackValue === null ? '' : String(fallbackValue).trim();

      if (preferMeta) {
        return metaText || baseText || fallbackText;
      }
      return baseText || metaText || fallbackText;
    };

    masks.forEach((mask, index) => {
      const meta = mask.objectMetadata;
      if (!meta) return;

      const existing = nextObjects[index];
      const fallback: SceneObject = {
        description: mask.promptObject || `object ${index + 1}`,
        location: 'center',
        relative_size: 'medium',
        shape_and_color: '',
        orientation: 'front-facing',
      };

      const base = existing ? { ...existing } : fallback;
      const preferMeta = !existing || isPlaceholderObject(base);
      const updated: SceneObject = {
        description: pickValue(base.description, meta.description, fallback.description, preferMeta),
        location: pickValue(base.location, meta.location, fallback.location, preferMeta) as SceneObject['location'],
        relationship: pickValue(base.relationship, meta.relationship, fallback.relationship, preferMeta),
        relative_size: pickValue(base.relative_size, meta.relative_size, fallback.relative_size, preferMeta) as SceneObject['relative_size'],
        shape_and_color: pickValue(base.shape_and_color, meta.shape_and_color, fallback.shape_and_color, preferMeta),
        texture: pickValue(base.texture, meta.texture, fallback.texture, preferMeta),
        appearance_details: pickValue(
          base.appearance_details,
          meta.appearance_details,
          fallback.appearance_details,
          preferMeta
        ),
        orientation: pickValue(base.orientation, meta.orientation, fallback.orientation, preferMeta) as SceneObject['orientation'],
      };

      nextObjects[index] = updated;
    });

    return nextObjects;
  };

  const buildRefineConfig = (
    baseConfig: PenguinConfig,
    baseSceneConfig: SceneConfiguration,
    fallbackStructured: Record<string, unknown> | null
  ): PenguinConfig => {
    const resolveShortDescription = (): string => {
      const current =
        typeof baseConfig.short_description === 'string' ? baseConfig.short_description.trim() : '';
      if (current.length >= 10) return current;

      const structured = fallbackStructured as Record<string, unknown> | null;
      const candidate =
        (structured?.short_description as string) ||
        (structured?.context as string) ||
        (structured?.background_setting as string);
      if (typeof candidate === 'string' && candidate.trim().length >= 10) {
        return candidate.trim();
      }

      const objectDescriptions = Array.isArray(baseConfig.objects)
        ? baseConfig.objects
          .map((obj) => obj.description)
          .filter((value) => typeof value === 'string' && value.trim())
        : [];
      if (objectDescriptions.length > 0) {
        return `Scene with ${objectDescriptions.slice(0, 3).join(', ')}`;
      }

      return 'A detailed scene ready for refinement';
    };

    return {
      ...baseConfig,
      short_description: resolveShortDescription(),
      background_setting: baseConfig.background_setting || baseSceneConfig.background_setting || '',
      aspect_ratio: baseConfig.aspect_ratio || baseSceneConfig.aspect_ratio || '1:1',
      lighting: {
        ...baseSceneConfig.lighting,
        ...baseConfig.lighting,
      },
      aesthetics: {
        ...baseSceneConfig.aesthetics,
        ...baseConfig.aesthetics,
      },
      photographic_characteristics: {
        ...baseSceneConfig.photographic_characteristics,
        ...baseConfig.photographic_characteristics,
      },
      style_medium:
        baseConfig.style_medium || baseSceneConfig.aesthetics.style_medium || 'photograph',
      artistic_style:
        baseConfig.artistic_style || baseSceneConfig.aesthetics.aesthetic_style || 'realistic',
      objects: buildObjectsFromSegmentationMetadata(
        Array.isArray(baseConfig.objects) ? baseConfig.objects : []
      ),
    };
  };

  const handleRefine = (promptOverride?: unknown): void => {
    const normalizedOverride = normalizePromptOverride(promptOverride);
    if (!hasVisualContext()) {
      generateImageRef.current?.(resolveGenerationPrompt(normalizedOverride, configRef.current));
      return;
    }

    // In edit mode, use the user's prompt (which may be the auto-generated one or their edits)
    const modificationPrompt = normalizedOverride ?? localPromptRef.current;

    const { config: storeConfig, sceneConfig, rawStructuredPrompt } = useConfigStore.getState();
    const fallbackStructured = originalStructuredPromptRef.current || rawStructuredPrompt || null;
    const mergedConfig = buildRefineConfig(storeConfig, sceneConfig, fallbackStructured);

    // Refine uses:
    // - Current config (with user modifications)
    // - Modification prompt (natural language description of changes)
    refineImageRef.current?.(
      mergedConfig,
      modificationPrompt || undefined
    );

    // Clear edits after refine (they've been applied)
    editTracker.clearEdits();
    setAutoGeneratedPrompt('');
    userEditedPromptRef.current = false;
  };

  const handleRefineWithConfig = (
    configOverride: PenguinConfig,
    promptOverride?: unknown,
    structuredOverride?: Record<string, unknown>
  ): void => {
    const normalizedOverride = normalizePromptOverride(promptOverride);
    if (!hasVisualContext()) {
      generateImageRef.current?.(resolveGenerationPrompt(normalizedOverride, configOverride));
      return;
    }

    const modificationPrompt = normalizedOverride ?? localPromptRef.current;
    const { sceneConfig, rawStructuredPrompt } = useConfigStore.getState();
    const fallbackStructured =
      structuredOverride || originalStructuredPromptRef.current || rawStructuredPrompt || null;
    const mergedConfig = buildRefineConfig(configOverride, sceneConfig, fallbackStructured);

    refineImageRef.current?.(
      mergedConfig,
      modificationPrompt || undefined
    );

    editTracker.clearEdits();
    setAutoGeneratedPrompt('');
    userEditedPromptRef.current = false;
  };

  const handleModeChange = (mode: PromptMode): void => {
    setPromptMode(mode);

    if (mode === 'edit') {
      // Reset user edit flag when entering edit mode with fresh auto-generated prompt
      userEditedPromptRef.current = false;

      // Generate modification prompt from tracked edits
      const modificationPrompt = editTracker.getModificationPrompt();
      setAutoGeneratedPrompt(modificationPrompt);

      // Populate the textarea with the auto-generated prompt
      if (modificationPrompt) {
        setLocalPrompt(modificationPrompt);
      }
    } else {
      // Switch back to generate mode - restore the short description or base prompt
      userEditedPromptRef.current = false;

      if (hasImageLoaded) {
        setLocalPrompt(shortDescription);
      } else {
        // No image: restore base prompt with any current edits
        const editPrompt = editTracker.getModificationPrompt();
        const base = baseUserPromptRef.current || '';
        if (editPrompt) {
          const separator = base.trim() ? ', ' : '';
          setLocalPrompt(base.trim() + separator + editPrompt);
        } else {
          setLocalPrompt(base);
        }
      }
      setAutoGeneratedPrompt('');
    }
  };

  const promptValue = activeMode === 'chat' ? chatPrompt : localPrompt;
  const handleUnifiedPromptChange = (value: string): void => {
    if (activeMode === 'chat') {
      setChatPrompt(value);
      return;
    }
    handlePromptChange(value);
  };

  const handleMaskHover = (maskId: string | null): void => {
    hoverMask(maskId);
  };

  const handleMaskClick = (maskId: string): void => {
    selectMask(selectedMaskId === maskId ? null : maskId);
  };

  const handleBackgroundDeselect = (): void => {
    selectMask(null);
  };

  useImperativeHandle(ref, () => ({
    handleGenerate,
    handleGenerateFromPrompt,
    handleRefine,
    handleRefineWithConfig,
  }), [handleGenerate, handleGenerateFromPrompt, handleRefine, handleRefineWithConfig]);

  useEffect(() => {
    const handlers = {
      handleGenerate: (promptOverride?: string) => handleGenerate(promptOverride),
      handleGenerateFromPrompt: (prompt: string) => handleGenerateFromPrompt(prompt),
      handleRefine: (promptOverride?: string) => handleRefine(promptOverride),
      handleRefineWithConfig: (
        configOverride: unknown,
        promptOverride?: string,
        structuredOverride?: unknown
      ) => {
        const safeConfig =
          (configOverride && typeof configOverride === 'object'
            ? configOverride
            : configRef.current) as PenguinConfig;
        const safeStructured =
          structuredOverride && typeof structuredOverride === 'object'
            ? (structuredOverride as Record<string, unknown>)
            : undefined;
        handleRefineWithConfig(safeConfig, promptOverride, safeStructured);
      },
    };
    setWorkspaceHandlers(handlers);
    return () => {
      setWorkspaceHandlers(undefined);
    };
    // setWorkspaceHandlers is stable from the store; handlers are stable closures using refs
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (selectedFileUrl && /\.(png|jpe?g)$/i.test(selectedFileUrl)) {
      setLibraryImage(selectedFileUrl);
      setViewMode('original');
      userViewModeOverrideRef.current = false;
      // Clear any previous generated image so library image shows (preserves seed)
      clearGeneratedImage();
    } else {
      setLibraryImage(null);
    }
  }, [selectedFileUrl, clearGeneratedImage]);

  // Set seed when loading a generation from library
  useEffect(() => {
    setSeed(currentSeed ?? null);
  }, [currentSeed, setSeed]);

  // Clear stale refinement context when no visual context exists
  useEffect(() => {
    const hasVisual =
      !!generatedImage ||
      !!libraryImage ||
      !!selectedFileUrl ||
      !!currentGenerationId ||
      !!segmentationResults?.original_image_url;

    if (!hasVisual && !isLoading) {
      setSeed(null);
      setOriginalStructuredPrompt(null);
    }
  }, [
    generatedImage,
    libraryImage,
    selectedFileUrl,
    currentGenerationId,
    segmentationResults?.original_image_url,
    isLoading,
    setSeed,
    setOriginalStructuredPrompt,
  ]);

  // Clear library image when a new generation completes
  // This ensures the new generated image is shown instead of the old library selection
  useEffect(() => {
    if (generatedImage && libraryImage) {
      setLibraryImage(null);
    }
  }, [generatedImage, libraryImage]);

  // Auto-switch to segmented view when new segmentation results arrive,
  // unless the user explicitly toggled the view.
  const prevSegmentationRef = useRef(!!segmentationResults);
  useEffect(() => {
    const hadResults = prevSegmentationRef.current;
    const hasResults = !!segmentationResults;
    if (!hadResults && hasResults && !userViewModeOverrideRef.current) {
      setViewMode('segmented');
    }
    prevSegmentationRef.current = hasResults;
  }, [segmentationResults]);

  const showSegmentedView = viewMode === 'segmented' && segmentationResults;
  const showSegmentationOriginal = viewMode === 'original' && segmentationResults;

  // Priority: generatedImage > libraryImage > segmentation original
  const originalImageToShow = generatedImage
    ? generatedImage
    : libraryImage
      ? libraryImage
      : showSegmentationOriginal
        ? segmentationResults?.original_image_url || null
        : null;

  return (
    <main
      className="flex-1 flex flex-col min-w-[400px] overflow-hidden bg-background relative z-10"
      role="main"
      aria-label="Workspace panel"
    >
      <div className="flex-1 mt-2 p-6 md:p-8 overflow-y-auto studio-grid-bg relative">
        <div className="mb-6 flex gap-3 items-center animate-reveal">
          {segmentationResults && (
            <div className="flex p-0.5 gap-1 bg-muted/30 backdrop-blur-md border border-border/50 rounded-xl ml-auto">
              <Button
                size="sm"
                variant="ghost"
                className={`rounded-lg h-8 px-4 transition-all duration-300 ${viewMode === 'original' ? 'bg-card shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                onClick={() => {
                  userViewModeOverrideRef.current = true;
                  setViewMode('original');
                  selectMask(null);
                }}
              >
                Original
              </Button>
              <Button
                size="sm"
                variant="ghost"
                className={`rounded-lg h-8 px-4 transition-all duration-300 ${viewMode === 'segmented' ? 'bg-card shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                onClick={() => {
                  userViewModeOverrideRef.current = true;
                  setViewMode('segmented');
                }}
              >
                Segmented
              </Button>
            </div>
          )}
        </div>

        {showSegmentedView ? (
          <div
            className="relative w-full bg-muted/50 rounded-lg overflow-hidden border border-border"
            style={viewerStyle}
          >
            <Suspense fallback={<div className="w-full h-full flex items-center justify-center"><div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" /></div>}>
              <MaskViewer
                originalImageUrl={segmentationResults.original_image_url}
                masks={segmentationResults.masks}
                selectedMaskId={selectedMaskId}
                onMaskHover={handleMaskHover}
                onMaskClick={handleMaskClick}
                onBackgroundDeselect={handleBackgroundDeselect}
              />
            </Suspense>

            {/* {showShortcutsHelp && (
              <div className="absolute top-4 right-4 bg-background/95 backdrop-blur-sm border border-border rounded-lg shadow-lg p-4 max-w-xs">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold">Keyboard Shortcuts</h3>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => setShowShortcutsHelp(false)}
                    className="h-6 w-6 p-0"
                  >
                    ×
                  </Button>
                </div>
                <div className="space-y-2 text-xs">
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.cycleForward.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Tab</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.cycleBackward.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Shift+Tab</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.deselect.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Esc</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.toggleVisibility.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">M</kbd>
                  </div>
                </div>
              </div>
            )} */}
          </div>
        ) : segmentationError ? (
          <div
            className="relative w-full bg-muted/50 rounded-lg overflow-hidden border border-border"
            style={viewerStyle}
          >
            <ErrorOverlay
              error={segmentationError}
              errorCode={segmentationErrorCode || undefined}
              onRetry={retryLastOperation}
              isRetrying={isSegmenting}
            />
          </div>
        ) : (
          <ImageViewer
            image={originalImageToShow}
            isLoading={isLoading || isSegmenting}
            error={error}
            style={viewerStyle}
          />
        )}
      </div>

      <div className="border-t border-border p-5 md:p-6 bg-background/40 backdrop-blur-xl relative z-20">
        <div className="max-w-4xl mx-auto">
          <Suspense fallback={null}>
            <PromptControls
              prompt={promptValue}
              onPromptChange={handleUnifiedPromptChange}
              onGenerate={() => handleGenerate()}
              isLoading={isLoading}
              mode={promptMode}
              onModeChange={activeMode === 'edit' ? handleModeChange : undefined}
              autoGeneratedPrompt={autoGeneratedPrompt}
              onAskAgent={(prompt) => {
                if (!prompt.trim()) return;
                sendAgentMessage(prompt);
                setChatPrompt('');
              }}
              isAskingAgent={isAgentTyping}
              showGenerateAction={activeMode === 'edit'}
              showAgentAction={activeMode === 'chat'}
              submitOnEnter={activeMode === 'chat'}
              placeholderOverride={activeMode === 'chat'
                ? 'Tell Penguin how to refine this image...'
                : undefined}
            />
          </Suspense>
        </div>
      </div>
    </main>
  );
});

WorkspacePanel.displayName = 'WorkspacePanel';
