import { useState, useEffect, useImperativeHandle, forwardRef, useRef } from 'react';
import { ImageViewer } from '@/features/imageEdit/components/ImageViewer';
import { MaskViewer } from '@/features/segmentation/components/MaskViewer';
import { PromptControls, type PromptMode } from '@/shared/components/PromptControls';
import { ErrorOverlay } from '@/shared/components/ErrorOverlay';
import { useConfigStore } from '@/features/scene/store/configStore';
import { useSegmentationStore } from '@/features/segmentation/store/segmentationStore';
import { useGeneration } from '@/shared/hooks/useGeneration';
import { useDebounce } from '@/shared/hooks/useDebounce';
import { useMaskKeyboardShortcuts } from '@/features/segmentation/hooks/useMaskKeyboardShortcuts';
import { Button } from '@/shared/components/ui/button';
import { useFileSystemStore } from '@/core/store/fileSystemStore';
import { useLayoutStore } from '@/core/store/layoutStore';
import { editTracker } from '@/shared/lib/editTracker';
import { useChatStore } from '@/features/agentic/store/chatStore';

export interface WorkspacePanelRef {
  handleGenerate: (promptOverride?: string) => void;
  handleRefine: (promptOverride?: string) => void;
}

type ViewMode = 'original' | 'segmented';



export const WorkspacePanel = forwardRef<WorkspacePanelRef>((_props, ref) => {
  const shortDescription = useConfigStore((state) => state.config.short_description);
  const config = useConfigStore((state) => state.config);
  const updateConfig = useConfigStore((state) => state.updateConfig);
  const setWorkspaceHandlers = useLayoutStore((state) => state.setWorkspaceHandlers);
  const activeMode = useLayoutStore((state) => state.activeMode);
  const selectedFileUrl = useFileSystemStore((state) => state.selectedFileUrl);
  const sendAgentMessage = useChatStore((state) => state.sendMessage);
  const isAgentTyping = useChatStore((state) => state.isTyping);
  const connectAgent = useChatStore((state) => state.connect);


  const safeShortDescription = typeof shortDescription === 'string' ? shortDescription : '';
  const [localPrompt, setLocalPrompt] = useState(safeShortDescription);
  const [chatPrompt, setChatPrompt] = useState('');
  const debouncedPrompt = useDebounce(localPrompt, 300);
  const [viewMode, setViewMode] = useState<ViewMode>('original');
  const userViewModeOverrideRef = useRef(false);
  const [promptMode, setPromptMode] = useState<PromptMode>('generate');
  const [autoGeneratedPrompt, setAutoGeneratedPrompt] = useState<string>('');

  // Track if user has manually edited the prompt in edit mode (to avoid overwriting their changes)
  const userEditedPromptRef = useRef(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const metadataInputRef = useRef<HTMLInputElement>(null);

  const { generateImage, refineImage, setSeed, clearGeneratedImage, isLoading, generatedImage, error } = useGeneration();
  const currentSeed = useFileSystemStore((state) => state.currentSeed);
  const originalStructuredPrompt = useFileSystemStore((state) => state.originalStructuredPrompt);
  const [libraryImage, setLibraryImage] = useState<string | null>(null);
  const viewerStyle: React.CSSProperties = {
    width: '100%',
    height: 'calc(100vh - 300px)',
    maxHeight: 'calc(100vh - 150px)',
    minHeight: '360px',
  };

  const segmentationResults = useSegmentationStore((state) => state.results);
  const selectedMaskId = useSegmentationStore((state) => state.selectedMaskId);
  const isSegmenting = useSegmentationStore((state) => state.isProcessing);
  const segmentationError = useSegmentationStore((state) => state.error);
  const segmentationErrorCode = useSegmentationStore((state) => state.errorCode);
  const uploadImage = useSegmentationStore((state) => state.uploadImage);
  const selectMask = useSegmentationStore((state) => state.selectMask);
  const hoverMask = useSegmentationStore((state) => state.hoverMask);
  const retryLastOperation = useSegmentationStore((state) => state.retryLastOperation);
  const resetConfig = useConfigStore((state) => state.resetConfig);

  useMaskKeyboardShortcuts({ enabled: viewMode === 'segmented' && !!segmentationResults });

  useEffect(() => {
    connectAgent();
  }, [connectAgent]);

  // Track if this is a fresh mount (no image context)
  const isInitialMountRef = useRef(true);

  // Reset config to defaults on initial mount if no image is loaded
  // This ensures fresh sessions start with empty/default config
  useEffect(() => {
    if (!isInitialMountRef.current) return;
    isInitialMountRef.current = false;

    const hasImage = generatedImage || selectedFileUrl || segmentationResults?.original_image_url;
    if (!hasImage) {
      // Clear persisted storage for truly fresh sessions
      try {
        localStorage.removeItem('penguin-config-storage');
      } catch (e) {
        console.warn('[WorkspacePanel] Failed to clear localStorage:', e);
      }
      resetConfig();
      setLocalPrompt('');
      baseUserPromptRef.current = '';
      editTracker.clearEdits();
    }
    // Only run on mount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Sync local prompt to config store (only when user types, not when config is loaded)
  useEffect(() => {
    if (activeMode !== 'edit') return;
    const safePrompt = typeof debouncedPrompt === 'string' ? debouncedPrompt : '';
    if (safePrompt !== safeShortDescription && promptMode === 'generate') {
      updateConfig('short_description', safePrompt);
    }
  }, [debouncedPrompt, safeShortDescription, updateConfig, promptMode, activeMode]);

  // Check if we have an image loaded (for determining edit behavior)
  // Use originalImageToShow calculation to be consistent
  const hasImageLoaded = !!(generatedImage || libraryImage || segmentationResults?.original_image_url);

  // Track the base prompt (user-typed portion) separately from edit additions
  const baseUserPromptRef = useRef('');

  // Sync config store to local prompt (when config is loaded externally)
  // Only sync if we're not currently editing and no edits are pending
  useEffect(() => {
    if (activeMode !== 'edit') return;
    if (editTracker.hasEdits()) return;

    const nextShort = safeShortDescription;
    if (nextShort !== localPrompt && promptMode === 'generate' && document.activeElement?.id !== 'prompt-input') {
      setLocalPrompt(nextShort);
      if (!hasImageLoaded) {
        baseUserPromptRef.current = nextShort;
      }
    }
  }, [safeShortDescription, localPrompt, promptMode, hasImageLoaded, activeMode]);

  // Live-update prompt based on edits
  // - If image is loaded and in edit mode: update refine prompt
  // - If no image is loaded: append edits to generation prompt in real-time
  useEffect(() => {
    if (activeMode !== 'edit') return;

    const unsubscribe = editTracker.subscribe(() => {
      const editPrompt = editTracker.getModificationPrompt();
      // console.log('[EditTracker] Edit changed:', { editPrompt, hasImageLoaded, promptMode });

      if (hasImageLoaded) {
        // Image loaded: only update when in edit mode
        if (promptMode === 'edit') {
          setAutoGeneratedPrompt(editPrompt);
          // Only update localPrompt if user hasn't manually edited it
          if (!userEditedPromptRef.current) {
            setLocalPrompt(editPrompt);
          }
        }
      } else {
        // No image loaded: always append edits to generation prompt
        const base = baseUserPromptRef.current || '';
        if (editPrompt) {
          const separator = base.trim() ? ', ' : '';
          const combinedPrompt = base.trim() + separator + editPrompt;
          // console.log('[EditTracker] Setting combined prompt:', combinedPrompt);
          setLocalPrompt(combinedPrompt);
        } else {
          // No edits, restore base prompt
          setLocalPrompt(base);
        }
      }
    });

    return unsubscribe;
  }, [promptMode, hasImageLoaded, activeMode]);

  // Track user's base prompt (before edits are appended)
  const handlePromptChange = (value: string): void => {
    setLocalPrompt(value);

    // If in edit mode with image loaded, mark that user has manually edited
    // BUT only if the value differs from the auto-generated prompt (actual user edit)
    if (hasImageLoaded && promptMode === 'edit' && value !== autoGeneratedPrompt) {
      userEditedPromptRef.current = true;
    }

    // If no image loaded, we need to track the base prompt
    if (!hasImageLoaded) {
      const editPrompt = editTracker.getModificationPrompt();

      if (!editPrompt) {
        // No edits, entire value is the base
        baseUserPromptRef.current = value;
      } else {
        // There are edits - extract the base prompt from the value
        // The format is: "base prompt, edit1 and edit2"
        // We need to find where the edit part starts
        if (value.endsWith(editPrompt)) {
          // User kept the edit suffix, extract the base
          const editStart = value.lastIndexOf(editPrompt);
          let base = value.substring(0, editStart);
          // Remove trailing ", " or " "
          base = base.replace(/,\s*$/, '').trim();
          baseUserPromptRef.current = base;
        } else {
          // User modified the prompt (including edit part)
          // Treat the entire value as the new base and clear edits
          baseUserPromptRef.current = value;
          editTracker.clearEdits();
        }
      }
    }
  };

  const configRef = useRef(config);
  const localPromptRef = useRef(localPrompt);
  const generatedImageRef = useRef<string | null>(generatedImage);
  const generateImageRef = useRef(generateImage);
  const refineImageRef = useRef(refineImage);
  const libraryImageRef = useRef<string | null>(null);
  const originalStructuredPromptRef = useRef<Record<string, unknown> | null>(originalStructuredPrompt);

  useEffect(() => {
    configRef.current = config;
  }, [config]);

  useEffect(() => {
    localPromptRef.current = localPrompt;
  }, [localPrompt]);

  useEffect(() => {
    generatedImageRef.current = generatedImage;
  }, [generatedImage]);

  useEffect(() => {
    libraryImageRef.current = libraryImage;
  }, [libraryImage]);

  useEffect(() => {
    generateImageRef.current = generateImage;
  }, [generateImage]);

  useEffect(() => {
    refineImageRef.current = refineImage;
  }, [refineImage]);

  useEffect(() => {
    originalStructuredPromptRef.current = originalStructuredPrompt;
  }, [originalStructuredPrompt]);

  const handleGenerate = (promptOverride?: string): void => {
    if (promptMode === 'generate') {
      // Generate mode: uses just the text prompt (simple text-to-image)
      const rawPrompt = promptOverride ?? localPromptRef.current;
      const prompt =
        typeof rawPrompt === 'string' && rawPrompt !== '[object Object]'
          ? rawPrompt
          : safeShortDescription;

      if (!prompt || prompt === '[object Object]') {
        console.warn('[WorkspacePanel] Invalid prompt detected, aborting generate.');
        return;
      }

      generateImageRef.current?.(prompt);
    } else {
      // Edit mode: uses the modification prompt (user can edit the auto-generated one)
      handleRefine(promptOverride);
    }
  };

  const handleRefine = (promptOverride?: string): void => {
    // In edit mode, use the user's prompt (which may be the auto-generated one or their edits)
    const modificationPrompt = promptOverride ?? localPromptRef.current;

    // console.log('[Refine] Modification prompt:', modificationPrompt);
    // console.log('[Refine] Tracked edits:', editTracker.getEdits());

    // Refine uses:
    // - Current config (with user modifications)
    // - Modification prompt (natural language description of changes)
    // - Original structured prompt (baseline for Bria's modification mode)
    refineImageRef.current?.(
      configRef.current,
      modificationPrompt || undefined,
      originalStructuredPromptRef.current || undefined
    );

    // Clear edits after refine (they've been applied)
    editTracker.clearEdits();
    setAutoGeneratedPrompt('');
    userEditedPromptRef.current = false;
  };

  const handleModeChange = (mode: PromptMode): void => {
    setPromptMode(mode);

    if (mode === 'edit') {
      // Reset user edit flag when entering edit mode with fresh auto-generated prompt
      userEditedPromptRef.current = false;

      // Generate modification prompt from tracked edits
      const modificationPrompt = editTracker.getModificationPrompt();
      setAutoGeneratedPrompt(modificationPrompt);

      // Populate the textarea with the auto-generated prompt
      if (modificationPrompt) {
        setLocalPrompt(modificationPrompt);
      }
    } else {
      // Switch back to generate mode - restore the short description or base prompt
      userEditedPromptRef.current = false;

      if (hasImageLoaded) {
        setLocalPrompt(shortDescription);
      } else {
        // No image: restore base prompt with any current edits
        const editPrompt = editTracker.getModificationPrompt();
        const base = baseUserPromptRef.current || '';
        if (editPrompt) {
          const separator = base.trim() ? ', ' : '';
          setLocalPrompt(base.trim() + separator + editPrompt);
        } else {
          setLocalPrompt(base);
        }
      }
      setAutoGeneratedPrompt('');
    }
  };

  const promptValue = activeMode === 'chat' ? chatPrompt : localPrompt;
  const handleUnifiedPromptChange = (value: string): void => {
    if (activeMode === 'chat') {
      setChatPrompt(value);
      return;
    }
    handlePromptChange(value);
  };

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = event.target.files?.[0];
    if (!file) return;

    const metadataFile = metadataInputRef.current?.files?.[0];
    await uploadImage(file, metadataFile, localPrompt || shortDescription);
    setViewMode('segmented');
  };

  const handleMaskHover = (maskId: string | null): void => {
    hoverMask(maskId);
  };

  const handleMaskClick = (maskId: string): void => {
    selectMask(selectedMaskId === maskId ? null : maskId);
  };

  const handleBackgroundDeselect = (): void => {
    selectMask(null);
  };

  useImperativeHandle(ref, () => ({
    handleGenerate,
    handleRefine,
  }), []);

  useEffect(() => {
    const handlers = {
      handleGenerate,
      handleRefine,
    };
    setWorkspaceHandlers(handlers);
    return () => {
      setWorkspaceHandlers(undefined);
    };
    // setWorkspaceHandlers is stable from the store; handlers are stable closures using refs
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (selectedFileUrl && /\.(png|jpe?g)$/i.test(selectedFileUrl)) {
      setLibraryImage(selectedFileUrl);
      setViewMode('original');
      userViewModeOverrideRef.current = false;
      // Clear any previous generated image so library image shows (preserves seed)
      clearGeneratedImage();
    } else {
      setLibraryImage(null);
    }
  }, [selectedFileUrl, clearGeneratedImage]);

  // Set seed when loading a generation from library
  useEffect(() => {
    if (currentSeed !== null) {
      setSeed(currentSeed);
    }
  }, [currentSeed, setSeed]);

  // Clear library image when a new generation completes
  // This ensures the new generated image is shown instead of the old library selection
  useEffect(() => {
    if (generatedImage && libraryImage) {
      setLibraryImage(null);
    }
  }, [generatedImage, libraryImage]);

  // Auto-switch to segmented view when new segmentation results arrive,
  // unless the user explicitly toggled the view.
  const prevSegmentationRef = useRef(!!segmentationResults);
  useEffect(() => {
    const hadResults = prevSegmentationRef.current;
    const hasResults = !!segmentationResults;
    if (!hadResults && hasResults && !userViewModeOverrideRef.current) {
      setViewMode('segmented');
    }
    prevSegmentationRef.current = hasResults;
  }, [segmentationResults]);

  const showSegmentedView = viewMode === 'segmented' && segmentationResults;
  const showSegmentationOriginal = viewMode === 'original' && segmentationResults;

  // Priority: generatedImage > libraryImage > segmentation original
  const originalImageToShow = generatedImage
    ? generatedImage
    : libraryImage
      ? libraryImage
      : showSegmentationOriginal
        ? segmentationResults?.original_image_url || null
        : null;

  return (
    <main
      className="flex-1 flex flex-col min-w-[400px] overflow-hidden bg-background relative z-10"
      role="main"
      aria-label="Workspace panel"
    >
      <div className="flex-1 mt-2 p-6 md:p-8 overflow-y-auto studio-grid-bg relative">
        <div className="mb-6 flex gap-3 items-center animate-reveal">
          {segmentationResults && (
            <div className="flex p-0.5 gap-1 bg-muted/30 backdrop-blur-md border border-border/50 rounded-xl ml-auto">
              <Button
                size="sm"
                variant="ghost"
                className={`rounded-lg h-8 px-4 transition-all duration-300 ${viewMode === 'original' ? 'bg-card shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                onClick={() => {
                  userViewModeOverrideRef.current = true;
                  setViewMode('original');
                  selectMask(null);
                }}
              >
                Original
              </Button>
              <Button
                size="sm"
                variant="ghost"
                className={`rounded-lg h-8 px-4 transition-all duration-300 ${viewMode === 'segmented' ? 'bg-card shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'
                  }`}
                onClick={() => {
                  userViewModeOverrideRef.current = true;
                  setViewMode('segmented');
                }}
              >
                Segmented
              </Button>
            </div>
          )}
        </div>

        {showSegmentedView ? (
          <div
            className="relative w-full bg-muted/50 rounded-lg overflow-hidden border border-border"
            style={viewerStyle}
          >
            <MaskViewer
              originalImageUrl={segmentationResults.original_image_url}
              masks={segmentationResults.masks}
              selectedMaskId={selectedMaskId}
              onMaskHover={handleMaskHover}
              onMaskClick={handleMaskClick}
              onBackgroundDeselect={handleBackgroundDeselect}
            />

            {/* {showShortcutsHelp && (
              <div className="absolute top-4 right-4 bg-background/95 backdrop-blur-sm border border-border rounded-lg shadow-lg p-4 max-w-xs">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold">Keyboard Shortcuts</h3>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => setShowShortcutsHelp(false)}
                    className="h-6 w-6 p-0"
                  >
                    ×
                  </Button>
                </div>
                <div className="space-y-2 text-xs">
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.cycleForward.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Tab</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.cycleBackward.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Shift+Tab</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.deselect.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">Esc</kbd>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">{MASK_KEYBOARD_SHORTCUTS.toggleVisibility.description}</span>
                    <kbd className="px-2 py-1 bg-muted rounded text-xs font-mono">M</kbd>
                  </div>
                </div>
              </div>
            )} */}
          </div>
        ) : segmentationError ? (
          <div
            className="relative w-full bg-muted/50 rounded-lg overflow-hidden border border-border"
            style={viewerStyle}
          >
            <ErrorOverlay
              error={segmentationError}
              errorCode={segmentationErrorCode || undefined}
              onRetry={retryLastOperation}
              isRetrying={isSegmenting}
            />
          </div>
        ) : (
          <ImageViewer
            image={originalImageToShow}
            isLoading={isLoading || isSegmenting}
            error={error}
            style={viewerStyle}
          />
        )}
      </div>

      <div className="border-t border-border p-5 md:p-6 bg-background/40 backdrop-blur-xl relative z-20">
        <div className="max-w-4xl mx-auto">
          <PromptControls
            prompt={promptValue}
            onPromptChange={handleUnifiedPromptChange}
            onGenerate={handleGenerate}
            isLoading={isLoading}
            mode={promptMode}
            onModeChange={activeMode === 'edit' ? handleModeChange : undefined}
            autoGeneratedPrompt={autoGeneratedPrompt}
            onAskAgent={(prompt) => {
              if (!prompt.trim()) return;
              sendAgentMessage(prompt);
              setChatPrompt('');
            }}
            isAskingAgent={isAgentTyping}
            showGenerateAction={activeMode === 'edit'}
            showAgentAction={activeMode === 'chat'}
            submitOnEnter={activeMode === 'chat'}
            placeholderOverride={activeMode === 'chat'
              ? 'Tell Penguin how to refine this image...'
              : undefined}
          />
        </div>
      </div>
    </main>
  );
});

WorkspacePanel.displayName = 'WorkspacePanel';
